---
- name: Setup vcenter_folder
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a VM folder on given datacenter
      vcenter_folder:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: "{{ datacenter_name }}"
        folder_name: "{{ vmware_folder }}"
        folder_type: vm
        state: present
        validate_certs: False
- name: Create OSE vms 
  hosts: bootstrap_server,master_servers,minion_servers
  gather_facts: no
  # serial: 2
  tasks:
    - name: Clone the RedHat CoreOS template
      block:
        - name: Create vm
          vmware_guest:
            hostname: "{{ vcenter_hostname }}"
            username: "{{ vcenter_username }}"
            password: "{{ vcenter_password }}"
            validate_certs: False
            name: "{{ inventory_hostname }}"
            template: "{{ vm_template }}"
            datacenter: "{{ datacenter_name }}"
            folder: "{{ vmware_folder }}"
            datastore: "{{ datastore }}"
            state: poweredoff
            cluster: "{{ cluster_name }}"
            hardware:
                memory_mb: "{{ memory }}"
                num_cpus: "{{ num_cpu }}"
            customvalues:
                - key: "disk.EnableUUID"
                  value: "TRUE"
                - key: "guestinfo.ignition.config.data"
                  value: "{{ lookup('file', ign_template) | b64encode }}"
                - key: "guestinfo.ignition.config.data.encoding"
                  value: "base64"
            networks:
            - name: "{{ target_network }}"
            wait_for_ip_address: no
          delegate_to: localhost
          register: vminfo
        - name: Update MAC mac_address
          vmware_guest_network:
            hostname: "{{ vcenter_hostname }}"
            username: "{{ vcenter_username }}"
            password: "{{ vcenter_password }}"
            validate_certs: False
            name: "{{ inventory_hostname }}"
            networks:
            - label: "Network adapter 1"
              state: present
              manual_mac: "{{ mac_address }}"
          delegate_to: localhost